ROWS, COLS = 16, 16
BOUNDARY_CONDITIONS = 'periodic'

# grass
MAX_GRASS_GROWTH = 5

# cicadas
CICADAS_PER_GENE = 200
CICADAS_MAX_SATIETY = 5
CICADAS_HUNGER_RATE = 15
CICADAS_MATE_PROBABILITY = 90
CICADAS_AWAKING_DAY = 90
CICADAS_LONGEVITY = 365

# predators
PREDATORS = 100
PREDATORS_LONGEVITY = CICADAS_LONGEVITY
PREDATORS_MAX_SATIETY = CICADAS_MAX_SATIETY
PREDATORS_HUNGER_RATE = CICADAS_HUNGER_RATE
PREDATORS_MATE_PROBABILITY = CICADAS_MATE_PROBABILITY